[package]
name = "baby_step"
version = "0.1.0"
authors = ["Alexandre Chêne <kooparse@protonmail.com>"]
edition = "2018"

[dependencies]
gl = "0.6.0"
glutin= "0.19.0"
nalgebra = "0.16"
nalgebra-glm = "0.2"
image = "0.21.0"
ron = "*"
serde= "*"
notify="4.0.0"
